Replace Weather Underground API integration with Dark Sky API
jonatan-ivanov/slack-weather-status pull request #4
Opened 2019-03-28 22:07 UTC by srt4

The Weather Underground API has been turned off: https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api

2019-03-28 22:34 UTC, jonatan-ivanov requested changes
How about

`String emoji = ":${mapIconToSlackIcon(new String(condition?.icon?:"unknown"))}:"`

2019-03-28 22:36 UTC, jonatan-ivanov requested changes

2019-03-28 22:36 UTC, jonatan-ivanov commented on slack-weather.groovy
> +    def conditionRs = new RESTClient('https://api.darksky.net/').get(
How about 
def conditionRs = new RESTClient('https://api.darksky.net/').get(path: "/forecast/$darkSkyApiKey/$latitude,$longitude")

2019-04-09 22:18 UTC, srt4 commented on slack-weather.groovy
> +    def conditionRs = new RESTClient('https://api.darksky.net/').get(
Done

2019-04-09 22:19 UTC, srt4 commented
> How about
> 
> `String emoji = ":${mapIconToSlackIcon(new String(condition?.icon?:"unknown"))}:"`

Done

2019-04-09 22:39 UTC, merged